// Generated by https://quicktype.io

export interface ShipmentSend {
  address_from:                    { [key: string]: string };
  parcels:                         Parcel[];
  address_to:                      { [key: string]: string };
  consignment_note_class_code:     string;
  consignment_note_packaging_code: string;
}

export interface Parcel {
  weight:        number;
  distance_unit: string;
  mass_unit:     string;
  height:        number;
  width:         number;
  length:        number;
}
