// Generated by https://quicktype.io

export interface LabelsProps {
  data?: Data;
}

export interface Data {
  id?:         string;
  type?:       string;
  attributes?: Attributes;
}

export interface Attributes {
  created_at?:            string;
  updated_at?:            string;
  status?:                null | string;
  tracking_number?:       string;
  tracking_status?:       null;
  label_url?:             string;
  tracking_url_provider?: string;
  rate_id?:               number;
  error_message?:         Message[]
}

export interface Message {
  message?: string
}

export interface LabelState {
  data: LabelsProps,
  status: 'idle' | 'loading' | 'succeeded' | 'failed',
  error: string | undefined 
}

export interface LabelSend {
  rate_id:      number;
  label_format: string;
}